echo "rem Shares for terminal servers"
echo "if not exist \\\\$(hostname -s)\\ts goto fi"
echo "  rem Replace g: for terminal servers"
echo "  net use g: /delete /yes"
echo "  net use g: \\\\$(hostname -s)\\all_home_other\\%USERNAME%\\Groups /yes"
echo "  if not errorlevel 1 goto success"
echo "    echo Konnte Laufwerk G: (Gruppen-Dateien) nicht verbinden!"
echo "    pause"
echo "  :success"
echo "  rem Replace i: for terminal servers"
echo "  net use i: /delete /yes"
echo "  net use i: \\\\$(hostname -s)\\all_home_other\\%USERNAME%\\Windows /yes"
echo "  if not errorlevel 1 goto success"
echo "    echo Konnte Laufwerk I: (Windows-Profil) nicht verbinden!"
echo "    pause"
echo "  :success"
echo ":fi"
echo
